# Generated by Django 5.0.7 on 2024-07-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='age',
        ),
        migrations.AddField(
            model_name='customuser',
            name='identifier_name',
            field=models.CharField(default='default_identifier', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telegram_id',
            field=models.CharField(default='default_telegram_id', max_length=255),
        ),
    ]
