# Generated by Django 5.0.7 on 2024-07-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0002_remove_customuser_age_customuser_identifier_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fragment',
            field=models.CharField(blank=True, default='default_fragment', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='vpn_link',
            field=models.TextField(blank=True, default='default_vpn_link'),
        ),
    ]
