# Generated by Django 5.0.7 on 2024-07-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0003_customuser_fragment_customuser_vpn_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='fragment',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='vpn_link',
            field=models.TextField(blank=True),
        ),
    ]
