# Generated by Django 5.0.7 on 2024-07-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0004_alter_customuser_fragment_alter_customuser_vpn_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='fragment',
            field=models.CharField(blank=True, default='default_fragment', max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='vpn_link',
            field=models.TextField(blank=True, default='default_vpn_link'),
        ),
    ]
