# Generated by Django 5.0.7 on 2024-07-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0005_alter_customuser_fragment_alter_customuser_vpn_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='fragment',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
