# Generated by Django 5.0.7 on 2024-07-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0007_alter_customuser_vpn_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='month',
            field=models.CharField(blank=True, choices=[('1_month', '1_Month'), ('3_month', '3_Month'), ('6_month', '6_Month'), ('12_month', '12_Month')], default='1_month', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user',
            field=models.CharField(blank=True, choices=[('1_user', '1_User'), ('2_user', '2_User'), ('3_user', '3_User'), ('4_user', '4_User'), ('unlimited_user', 'Unlimited_user')], default='1_user', max_length=20),
        ),
    ]
