# Generated by Django 5.0.7 on 2024-07-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0008_customuser_month_customuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='type',
            field=models.CharField(blank=True, choices=[('vmess', 'Vmess'), ('vless', 'Vless')], default='vmess', max_length=20),
        ),
    ]
