# Generated by Django 5.0.7 on 2024-07-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0009_customuser_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='identifier_name',
            field=models.CharField(default='enter your identifier_name', max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telegram_id',
            field=models.CharField(default='enter your telegram_id', max_length=255),
        ),
    ]
